### ISSUE TITLE
needed to write this patch to extract slc.bin

### ISSUE THREAD

**Issue by anon8948** [GaryOderNichts/wiiu-nandextract-c#1]
Hi, I needed to write this patch to be able to extract my WiiU's SLC (or slc.bin file).

Without the patch, I got multiple complaints "this is not a superclusterthis is not a superclusterthis is not a supercluster" (missing an "\n" in the code) and so on, and ultimately the tool gave up and printed the message "can't find superblock!"

With the patch, I could extract my slc.bin successfully.
To be sure, I also extracted my slccmpt.bin again and that still worked too.

Thanks for the great tool, and I hope this makes it even greater.
Cheers.

The patch:
[patch.diff.txt](https://github.com/GaryOderNichts/wiiu-nandextract-c/files/5448605/patch.diff.txt)

**Comment by GaryOderNichts** [comment]
Thanks for the patch, but this should be already fixed with https://github.com/GaryOderNichts/wiiu-nandextract-c/commit/10d729c6df9d1fe6ad0621f125ddbc79832c2056
I haven't made a release since so this fix isn't in the latest release.
